    let appKeywords = {
        '트릭컬 리바이브': ['트릭컬 리바이브', '트릭컬'],
        '명조:워더링 웨이브': ['명조:워더링 웨이브', '명조', 'Wuthering Waves'],
        '가디언 테일즈': ['가디언 테일즈'],
        '쿠키런: 오븐브레이크': ['쿠키런: 오븐브레이크'],
        '블루 아카이브': ['블루 아카이브', 'Blue Archive'],
        '원신': ['원신', 'Genshin Impact'],
        '마비노기 모바일' : ['마비노기 모바일', '마비노기M'],
        '붕괴: 스타레일': ['붕괴: 스타레일', '붕괴스타레일','붕괴:스타레일'],
        '승리의 여신: 니케': ['승리의 여신: 니케', '니케', '승리의 여신:니케', 'GODDESS OF VICTORY: NIKKE'],
        '쿠키런: 킹덤': ['쿠키런: 킹덤', '쿠키런 킹덤', '쿠키런킹덤', '쿠키런:킹덤'],
        '명일방주': ['명일방주'],
        'Limbus Company': ['Limbus Company', '림버스 컴퍼니', '림버스컴퍼니'],
        '페이트/그랜드 오더': ['페이트/그랜드 오더', '페그오', 'Fate/Grand Order'],
        '에픽세븐': ['에픽세븐', '에픽 세븐', 'Epic Seven', ,'EpicSeven'],
        '우마무스메 프리티 더비': ['우마무스메', '우마무스메 프리티 더비', '우마무스메: 프리티 더비', '우마무스메프리티더비'],
        '브라운더스트2': ['브라운더스트2', '브라운더스트 2', '브라운더스트II', '브라운더스트 II'],
        '소녀전선2: 망명': ['소녀전선2', '소녀전선 2', '소녀전선2: 망명', '소녀전선2 망명', '소녀전선 망명'],
        '로스트 소드' : ['로스트 소드', 'Lost Sword'],
        '프린세스 커넥트! Re:Dive': ['프린세스 커넥트', '프린세스 커넥트! Re:Dive', '프린세스커넥트', '프린세스커넥트!Re:Dive'],
        '붕괴3rd': ['붕괴3rd', '붕괴 3rd', '붕괴3', '붕괴 3'],
        '젠레스 존 제로': ['젠레스 존 제로', '젠레스존제로', 'Zenless Zone Zero', 'ZenlessZoneZero'],
        '리버스: 1999': ['리버스 1999', '리버스1999', 'REVERSE 1999', '리버스: 1999', '리버스:1999', 'REVERSE: 1999', 'REVERSE:1999'],
        '에버소울': ['에버소울', 'Eversoul'],
        '스카이 킹덤：드래곤 에이지' : ['스카이 킹덤', '스카이 킹덤：드래곤 에이지', 'Sky Kingdom: Dragon Age'],
        'Merge Mansion' : ['Merge Mansion', '머지 맨션'],
        'Valkyrie Connect' : ['Valkyrie Connect', '발키리'],
        '포켓몬 카드 게임 Pocket': ['포켓몬 카드 게임 Pocket','포켓몬 카드 게임', '포켓몬카드게임', 'Pokémon TCG', 'Pokémon TCG Online'],
        '하스스톤': ['하스스톤', '하스스톤', 'Hearthstone'],
        'Yu-Gi-Oh! Duel Links': ['Yu-Gi-Oh! Duel Links', '유희왕 듀얼링크스', '유희왕 듀얼 링크스', '유희왕듀얼링크스'],
        'Yu-Gi-Oh! Master Duel': ['Yu-Gi-Oh! Master Duel', '유희왕 마스터 듀얼', '유희왕마스터듀얼'],
        '레조넌스': ['레조넌스', 'Resonance'],
        '신월동행' : ['신월동행', '신월 동행', 'New Moon Companion'],
        '벽람항로' : ['벽람항로', 'Azur Lane'],
        'Arcaea' : ['Arcaea', '아케아'],
        "Shadowverse: Worlds Beyond": ['Shadowverse', 'Shadowverse: Worlds Beyond', '섀도우버스', '섀도우버스: 월즈 비욘드'],
        "Monster Hunter Now": ['Monster Hunter Now', '몬스터 헌터 나우', '몬헌 나우', '몬헌나우'],
        'Pokémon GO': ['Pokémon GO','Pokemon GO', '포켓몬 GO', '포켓몬고', '포켓몬 GO'],
        'Pokémon Sleep': ['Pokémon Sleep','Pokemon Sleep', '포켓몬 Sleep', '포켓몬슬립', '포켓몬 Sleep'],
        '헤븐 번즈 레드' : ['헤븐 번즈 레드', '헤븐번즈레드', 'Heaven Burns Red'],
        'SD건담 지 제네레이션 이터널' : ['SD건담 지 제네레이션 이터널', 'SD건담지제네레이션이터널', 'SD Gundam G Generation Eternal'],
        '프로젝트 세카이 컬러풀 스테이지! feat. 하츠네 미쿠' : ['프로젝트 세카이', '프로젝트 세카이 컬러풀 스테이지! feat. 하츠네 미쿠', '프로젝트세카이컬러풀스테이지!feat.하츠네미쿠', 'Project Sekai: Colorful Stage! feat. Hatsune Miku'],
        '크루세이더 퀘스트' : ['크루세이더 퀘스트', '크루세이더퀘스트', 'Crusaders Quest'],
        '월드 플리퍼' : ['월드 플리퍼', '월드플리퍼', 'World Flipper'],
    };